<?php 

acfe_register_post_type(array(
    'name' => 'featured-item',
    'label' => 'Featured Items',
    'active' => true,
    'description' => '',
    'hierarchical' => false,
    'supports' => array(
        'title',
        'custom-fields',
    ),
    'taxonomies' => array(),
    'public' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'can_export' => true,
    'delete_with_user' => null,
    'labels' => array(
        'singular_name' => 'Featured Item',
        'add_new' => 'Add Featured Item',
        'add_new_item' => 'Add Featured Item',
        'edit_item' => 'Edit Featured Item',
        'new_item' => 'New Featured Item',
        'view_item' => 'View Featured Item',
        'view_items' => 'View Featured Items',
        'search_items' => 'Search Featured Items',
        'not_found' => 'Featured Item Not Found',
        'all_items' => 'All Featured Items',
    ),
    'menu_position' => '',
    'menu_icon' => 'dashicons-carrot',
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_admin_bar' => true,
    'has_archive' => false,
    'rewrite' => true,
    'capability_type' => 'post',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => true,
    'rest_base' => 'featured-items',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => '',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 25,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
    'acfe_autosync' => array(
        'php',
        'json',
    ),
    'modified' => 1702924917,
));

