<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_654c446cd50cd',
	'title' => 'Circulars',
	'fields' => array(
		array(
			'key' => 'field_654c446be1ff9',
			'label' => 'Circular Image',
			'name' => 'arg_circular_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Image dimensions must be 1024x1024.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'uploader' => 'wp',
			'return_format' => 'url',
			'library' => 'all',
			'upload_folder' => '',
			'acfe_thumbnail' => 1,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => 1200,
			'min_height' => 1200,
			'min_size' => '',
			'max_width' => 1200,
			'max_height' => 1200,
			'max_size' => '',
			'mime_types' => 'jpg, jpeg',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_654c451de1ffa',
			'label' => 'Start Date',
			'name' => 'arg_circular_start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Set a circular item start date.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'm/d/Y',
			'return_format' => 'm/d/Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_654c454ee1ffb',
			'label' => 'End Date',
			'name' => 'arg_circular_end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Set a circular item end date.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'm/d/Y',
			'return_format' => 'm/d/Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_654c4e1f6a710',
			'label' => 'Circular Heading',
			'name' => 'arg_circular_heading',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_654c4e346a711',
			'label' => 'Circular Subheading',
			'name' => 'arg_circular_subheading',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'instruction_placement' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_654c4ea56a712',
			'label' => 'Circular Details',
			'name' => 'circular_details',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'rows' => 3,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_654cdec1e4aee',
			'label' => 'Circular Rating',
			'name' => 'circular_rating',
			'aria-label' => '',
			'type' => 'range',
			'instructions' => 'Ratings are not required but do help with customer interaction.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min' => 0,
			'max' => 5,
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'step' => '.5',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'circular',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 1,
	'acfe_display_title' => 'Digital Circulars • Powered by Alliance Retail Group',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1700160893,
));

endif;