<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_64c05de4b9ba5',
	'title' => 'Promos',
	'fields' => array(
		array(
			'key' => 'field_64c05de4e9a3a',
			'label' => 'Promo Image',
			'name' => 'arg_promo_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Image dimensions must be set at 1920x750.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'uploader' => 'wp',
			'return_format' => 'url',
			'library' => 'all',
			'upload_folder' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => 1920,
			'min_height' => 750,
			'min_size' => '',
			'max_width' => 1920,
			'max_height' => 750,
			'max_size' => '',
			'mime_types' => 'jpg, jpeg, png',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_64c15323305b2',
			'label' => 'Promo Offer URL',
			'name' => 'arg_promo_offer_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_64c05de4e9ab4',
			'label' => 'Promo Start Date',
			'name' => 'arg_promo_start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_64c05de4e9aee',
			'label' => 'Promo End Date',
			'name' => 'arg_promo_end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_64c05de4e9b28',
			'label' => 'Promo Location',
			'name' => 'arg_promo_location',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'post_type' => array(
				0 => 'location',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
			'acfe_add_post' => 0,
			'acfe_edit_post' => 1,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => true,
				'acfe_bidirectional_related' => array(
					0 => 'field_64d2ac2b33504',
				),
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min' => '',
			'max' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'elements' => '',
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'promo',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 1,
	'acfe_display_title' => 'Alliance Plus Offers • Powered by Alliance Retail Group',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1700160988,
));

endif;