<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_64665be39c47d',
	'title' => 'Locations',
	'fields' => array(
		array(
			'key' => 'field_64665be3ef751',
			'label' => 'Location Details',
			'name' => 'arg_location_details',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Please use the fields provided to update the details of your location.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_6466b4b31de99',
					'label' => 'Location Address',
					'name' => 'arg_location_address',
					'aria-label' => '',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'center_lat' => '39.0997265',
					'center_lng' => '-94.5785667',
					'height' => 200,
					'acfe_google_map_zooms' => array(
						'zoom' => '12',
						'min_zoom' => '12',
						'max_zoom' => '17',
					),
					'acfe_google_map_marker_icon' => '',
					'acfe_google_map_marker_width' => 50,
					'acfe_google_map_type' => 'roadmap',
					'acfe_google_map_disable_ui' => 1,
					'acfe_google_map_style' => '',
					'acfe_google_map_key' => 'AIzaSyBKh7nadldo40hwf95hLg89SkOdbcaK8PU',
					'zoom' => '12',
					'acfe_google_map_marker_height' => 50,
					'acfe_google_map_disable_zoom_control' => false,
					'acfe_google_map_disable_map_type' => false,
					'acfe_google_map_disable_fullscreen' => false,
					'acfe_google_map_disable_streetview' => false,
				),
				array(
					'key' => 'field_64665c62a90e4',
					'label' => 'Location Phone Number',
					'name' => 'arg_location_phone_number',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64665cb8a90e6',
					'label' => 'Location Hours',
					'name' => 'arg_location_hours',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'acfe_repeater_stylised_button' => 1,
					'layout' => 'block',
					'pagination' => 0,
					'min' => 5,
					'max' => 7,
					'collapsed' => '',
					'button_label' => 'Add Location Hours',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_64665cfba90e7',
							'label' => 'Day of Operation',
							'name' => 'arg-location-hours-day_of_operation',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'choices' => array(
								'## Week Days' => '## Week Days',
								'Monday' => 'Monday',
								'Tuesday' => 'Tuesday',
								'Wednesday' => 'Wednesday',
								'Thursday' => 'Thursday',
								'Friday' => 'Friday',
								'##Weekends' => '##Weekends',
								'Saturday' => 'Saturday',
								'Sunday' => 'Sunday',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'placeholder' => 'Select Day',
							'prepend' => '',
							'append' => '',
							'max' => '',
							'allow_null' => 1,
							'ui' => 0,
							'ajax' => 0,
							'allow_custom' => 0,
							'search_placeholder' => '',
							'min' => '',
							'parent_repeater' => 'field_64665cb8a90e6',
						),
						array(
							'key' => 'field_64665dc0a90e8',
							'label' => 'Opening Hours',
							'name' => 'arg-location-hours-opening_hours',
							'aria-label' => '',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'display_format' => 'g:i A',
							'return_format' => 'g:i A',
							'placeholder' => '',
							'min_time' => '',
							'max_time' => '',
							'min_hour' => '',
							'max_hour' => '',
							'min_min' => '',
							'max_min' => '',
							'min_sec' => '',
							'max_sec' => '',
							'parent_repeater' => 'field_64665cb8a90e6',
						),
						array(
							'key' => 'field_64665e0aa90e9',
							'label' => 'Closing Hours',
							'name' => 'arg-location-hours-closing_hours',
							'aria-label' => '',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'display_format' => 'g:i A',
							'return_format' => 'g:i A',
							'placeholder' => '',
							'min_time' => '',
							'max_time' => '',
							'min_hour' => '',
							'max_hour' => '',
							'min_min' => '',
							'max_min' => '',
							'min_sec' => '',
							'max_sec' => '',
							'parent_repeater' => 'field_64665cb8a90e6',
						),
					),
				),
			),
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6466c80d8b266',
			'label' => 'Location URLs',
			'name' => 'arg_location_urls',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Please use the fields provided to update the social media URLs of your location.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_64d39259d1c89',
					'label' => 'Location Email Address',
					'name' => 'arg_location_email_address',
					'aria-label' => '',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647e18b1aef1c',
					'label' => 'Location Facebook URL',
					'name' => 'arg_location_facebook_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_647e1908aef1d',
					'label' => 'Location Instagram URL',
					'name' => 'arg_location_instagram_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_647e1942aef1e',
					'label' => 'Location LinkedIn URL',
					'name' => 'arg_location_linkedin_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_647e1991aef20',
					'label' => 'Location TikTok URL',
					'name' => 'arg_location_tiktok_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_647e1983aef1f',
					'label' => 'Location Twitter URL',
					'name' => 'arg_location_twitter_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
			),
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6466c78b8b265',
			'label' => 'Miscellaneous Items',
			'name' => 'arg_location_miscellaneous_items',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Please use the fields provided to update the miscellaneous details of your location.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_64665c7ca90e5',
					'label' => 'Location Description',
					'name' => 'arg_location_description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'acfe_wysiwyg_height' => 150,
					'acfe_wysiwyg_max_height' => '',
					'acfe_wysiwyg_valid_elements' => '',
					'acfe_wysiwyg_custom_style' => '',
					'acfe_wysiwyg_disable_wp_style' => 0,
					'acfe_wysiwyg_autoresize' => 0,
					'acfe_wysiwyg_disable_resize' => 0,
					'acfe_wysiwyg_remove_path' => 0,
					'acfe_wysiwyg_menubar' => 0,
					'acfe_wysiwyg_transparent' => 0,
					'acfe_wysiwyg_merge_toolbar' => 0,
					'acfe_wysiwyg_custom_toolbar' => 0,
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'acfe_wysiwyg_auto_init' => 0,
					'acfe_wysiwyg_min_height' => 300,
					'acfe_wysiwyg_toolbar_buttons' => array(
					),
				),
				array(
					'key' => 'field_646aa502f6f2a',
					'label' => 'Location Weekly Ads',
					'name' => 'arg_location_weekly_ads',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'post_type' => array(
						0 => 'weekly-ad',
					),
					'post_status' => '',
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'return_format' => 'object',
					'acfe_add_post' => 1,
					'acfe_edit_post' => 1,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '1',
						'acfe_bidirectional_related' => array(
							0 => 'field_646aa440c9ec8',
							1 => 'field_646aa502f6f2a',
						),
					),
					'min' => '',
					'max' => '',
					'elements' => '',
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_64c3ef6e8093b',
					'label' => 'Location Departments',
					'name' => 'arg_location_departments',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'post_type' => array(
						0 => 'department',
					),
					'post_status' => '',
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'return_format' => 'object',
					'acfe_add_post' => 1,
					'acfe_edit_post' => 1,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => true,
						'acfe_bidirectional_related' => array(
							0 => 'field_64c26f909b962',
							1 => 'field_64c3ef6e8093b',
						),
					),
					'min' => '',
					'max' => '',
					'elements' => '',
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_64d2ac2b33504',
					'label' => 'Location Promotions',
					'name' => 'arg_location_promotions',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'post_type' => array(
						0 => 'promo',
					),
					'post_status' => '',
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'return_format' => 'object',
					'acfe_add_post' => 1,
					'acfe_edit_post' => 1,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '1',
						'acfe_bidirectional_related' => array(
							0 => 'field_64c05de4e9b28',
						),
					),
					'min' => '',
					'max' => '',
					'elements' => '',
					'bidirectional_target' => array(
					),
				),
			),
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'location',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_display_title' => 'Locations • Powered by Alliance Retail Group',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1700160977,
));

endif;