<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6580a2cd07329',
	'title' => 'Featured Items',
	'fields' => array(
		array(
			'key' => 'field_6580a2cd45da7',
			'label' => 'Featured Item Image',
			'name' => 'arg_featured_item_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Image must be a JPG and at a 850x850 resolution.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'uploader' => 'wp',
			'return_format' => 'url',
			'library' => 'all',
			'upload_folder' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => 850,
			'min_height' => 850,
			'min_size' => '',
			'max_width' => 850,
			'max_height' => 850,
			'max_size' => '',
			'mime_types' => 'jpg, jpeg',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'preview_size' => 'thumbnail',
		),
		array(
			'key' => 'field_6580a2cd45e90',
			'label' => 'Featured Item Start Date',
			'name' => 'arg_featured_item_start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_6580a2cd45ecb',
			'label' => 'Featured Item End Date',
			'name' => 'arg_featured_item_end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_save_meta' => 0,
			'instruction_placement' => '',
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_6580a2cd45e53',
			'label' => 'Featured Item Price',
			'name' => 'arg_featured_item_price',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_save_meta' => 0,
			'instruction_placement' => '',
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6580a2cd45e1b',
			'label' => 'Featured Item Desciption',
			'name' => 'arg_featured_item_desciption',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'featured-item',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'author',
		1 => 'block_editor',
		2 => 'categories',
		3 => 'comments',
		4 => 'the_content',
		5 => 'discussion',
		6 => 'excerpt',
		7 => 'featured_image',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'revisions',
		11 => 'send-trackbacks',
		12 => 'tags',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 1,
	'acfe_display_title' => 'Featured Items • Powered by Alliance Retail Group',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1703020412,
));

endif;