<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6477969146042',
	'title' => 'Recipes',
	'fields' => array(
		array(
			'key' => 'field_64779691af264',
			'label' => 'Recipe Hero Section',
			'name' => 'recipe_hero_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Please use the fields provided to update the hero section of your recipe.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_647797a6af265',
					'label' => 'Recipe Hero Image',
					'name' => 'arg-recipe_hero_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => 'Image size dimensions are 2560x1500.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'uploader' => 'wp',
					'return_format' => 'url',
					'library' => 'all',
					'upload_folder' => '',
					'acfe_thumbnail' => 1,
					'required_message' => '',
					'min_width' => 2560,
					'min_height' => 1500,
					'min_size' => '',
					'max_width' => 2560,
					'max_height' => 1500,
					'max_size' => '',
					'mime_types' => 'jpg, jpeg',
					'preview_size' => 'thumbnail',
				),
				array(
					'key' => 'field_64779817af266',
					'label' => 'Recipe Hero Subtitle',
					'name' => 'arg-recipe_hero_subtitle',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_field' => '',
					'hide_label' => '',
					'hide_instructions' => '',
					'hide_required' => '',
					'acfe_save_meta' => 0,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'instruction_placement' => '',
					'acfe_permissions' => array(
						0 => 'administrator',
					),
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647798ccaf267',
					'label' => 'Recipe Hero Copy',
					'name' => 'arg-recipe_hero_copy',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'acfe_wysiwyg_height' => 150,
					'acfe_wysiwyg_max_height' => '',
					'acfe_wysiwyg_valid_elements' => '',
					'acfe_wysiwyg_custom_style' => '',
					'acfe_wysiwyg_disable_wp_style' => 0,
					'acfe_wysiwyg_autoresize' => 0,
					'acfe_wysiwyg_disable_resize' => 0,
					'acfe_wysiwyg_remove_path' => 0,
					'acfe_wysiwyg_menubar' => 0,
					'acfe_wysiwyg_transparent' => 0,
					'acfe_wysiwyg_merge_toolbar' => 0,
					'acfe_wysiwyg_custom_toolbar' => 0,
					'required_message' => '',
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'acfe_wysiwyg_auto_init' => 0,
					'acfe_wysiwyg_min_height' => 300,
					'acfe_wysiwyg_toolbar_buttons' => array(
					),
				),
				array(
					'key' => 'field_64779960af268',
					'label' => 'Recipe Total Time',
					'name' => 'arg-recipe_total_time',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'required_message' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647799fdaf269',
					'label' => 'Recipe Total Prep Time',
					'name' => 'arg-recipe_total_prep_time',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'required_message' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64779a13af26a',
					'label' => 'Recipe Total Cook Time',
					'name' => 'arg-recipe_total_cook_time',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'required_message' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64f9fa445486e',
					'label' => 'Recipe Serving Size',
					'name' => 'arg-recipe_serving_size',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'required_message' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64779aaeaf26b',
					'label' => 'Recipe Difficulty Level',
					'name' => 'arg-recipe_difficulty_level',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'<i class="fa-solid fa-hat-chef fa-2x uk-text-primary"></i> <i class="fa-solid fa-hat-chef fa-2x uk-text-primary"></i> <i class="fa-solid fa-hat-chef fa-2x uk-text-primary"></i>' => 'High',
						'<i class="fa-solid fa-hat-chef fa-2x uk-text-primary"></i> <i class="fa-solid fa-hat-chef fa-2x uk-text-primary"></i> <i class="fa-solid fa-hat-chef fa-2x uk-text-muted"></i>' => 'Medium',
						'<i class="fa-solid fa-hat-chef fa-2x uk-text-primary"></i> <i class="fa-solid fa-hat-chef fa-2x uk-text-muted"></i> <i class="fa-solid fa-hat-chef fa-2x uk-text-muted"></i>' => 'Low',
					),
					'default_value' => '',
					'return_format' => 'value',
					'required_message' => '',
					'allow_null' => 1,
					'other_choice' => 0,
					'layout' => 'horizontal',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6477a00558084',
					'label' => 'Recipe Video URL',
					'name' => 'arg-recipe_video_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_64779d846292b',
			'label' => 'Recipe Step Details',
			'name' => 'arg-recipe_step_details',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Please use the fields provided to update the steps needed to complete your recipe.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_settings' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_64779d9c6292c',
					'label' => 'Recipe Steps',
					'name' => 'arg-recipe_steps',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_field' => '',
					'hide_label' => '',
					'hide_instructions' => '',
					'hide_required' => '',
					'acfe_save_meta' => 0,
					'acfe_repeater_stylised_button' => 1,
					'layout' => 'table',
					'pagination' => 0,
					'acfe_settings' => '',
					'required_message' => '',
					'min' => 2,
					'max' => 0,
					'instruction_placement' => '',
					'acfe_permissions' => '',
					'collapsed' => '',
					'button_label' => 'Add New Step',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_64779dd26292d',
							'label' => 'Recipe Step',
							'name' => 'recipe_step',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'acfe_textarea_code' => 0,
							'maxlength' => '',
							'rows' => 3,
							'placeholder' => '',
							'new_lines' => '',
							'parent_repeater' => 'field_64779d9c6292c',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_64779e246292e',
			'label' => 'Recipe Ingredient Details',
			'name' => 'arg-recipe_ingredient_details',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Please use the fields provided to update the ingredients needed to complete your recipe.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_64779e246292f',
					'label' => 'Recipe Ingredients',
					'name' => 'arg-recipe_ingredients',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'acfe_repeater_stylised_button' => 1,
					'layout' => 'table',
					'pagination' => 0,
					'required_message' => '',
					'min' => 2,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add New Ingredient',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_64779e2462930',
							'label' => 'Recipe Ingredient',
							'name' => 'arg-recipe_ingredient',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_64779e246292f',
						),
						array(
							'key' => 'field_64779ef862931',
							'label' => 'Recipe Ingredient Serving',
							'name' => 'arg-recipe_ingredient_serving',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_64779e246292f',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'recipe',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'author',
		1 => 'block_editor',
		2 => 'categories',
		3 => 'comments',
		4 => 'the_content',
		5 => 'discussion',
		6 => 'excerpt',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'revisions',
		10 => 'send-trackbacks',
		11 => 'tags',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 1,
	'acfe_display_title' => 'Recipes • Powered by Alliance Retail Group',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1700161002,
));

endif;