<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_64c41fada5723',
	'title' => 'Alerts',
	'fields' => array(
		array(
			'key' => 'field_64c41fada9c3f',
			'label' => 'Alert Start Date',
			'name' => 'arg_alert_start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_64c41fada9c78',
			'label' => 'Alert End Date',
			'name' => 'arg_alert_end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
		),
		array(
			'key' => 'field_64c41fada9cfe',
			'label' => 'Alert Copy',
			'name' => 'arg_alert_copy',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Keep this short and to the point. Try to keep the alert on one line when viewing on desktop.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => 200,
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_64c41fada9c07',
			'label' => 'Alert URL',
			'name' => 'arg_alert_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Please only include if needed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'alert',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 1,
	'acfe_display_title' => 'Alliance Plus Offers • Powered by Alliance Retail Group',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1702067648,
));

endif;